// STATIC METADATA
export const metadata = {
    title : "About Codevolution",
    description : "Generated By About Page ( Shashi )"
}

const About = () => {
  return (
    <div>About Page</div>
  )
}

export default About